info:
   app:
      name: ${info.maven.name}
      description: ${info.maven.description}
      env: ${environment.name}
   maven:
      artifactId: ^project.artifactId^
      name: ^project.name^
      description: ^project.description^
      version: ^project.version^
      parent: ^project.parent.artifactId^
      group: ^project.parent.groupId^
management:
   endpoints:
      web:
         base-path: /manage
server:
  port: 8091
spring:
  application:
    name: ${info.maven.name}
environment:
  name: default
  
client:
   feign:
      enabled: true
      fallback:
         enabled: false
      timeout:
         connection: 5000
         read: 5000
  
ecommerce:
  username: ${USERNAME}
  password: ${PASSWORD}
  auth-url: ${AUTH_URL:http://docker.for.mac.localhost:8090}
  token-expiry: 30
